services:
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mynetwork

  adminer:
    container_name: adminer
    image: adminer
    platform: linux/x86_64
    ports:
      - 8080:8080
    networks:
      - mynetwork

  migrations:
    container_name: migrations
    build:
      context: ./task_migrations
    platform: linux/x86_64
    volumes:
      - ./task_migrations:/rails
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "bundle exec rails db:create &&  bundle exec rails db:migrate &&  bundle exec rails db:migrate RAILS_ENV=test &&  bundle exec rails db:seed"
    env_file:
      - .env
    networks:
      - mynetwork

  auth:
    container_name: auth
    build:
      context: ./auth_service
    platform: linux/x86_64
    volumes:
      - ./auth_service:/rails
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3001:3000
    networks:
      - mynetwork

  notifications:
    container_name: notifications
    build:
      context: ./notification_service
    platform: linux/x86_64
    volumes:
      - ./notification_service:/rails
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3002:3000
    networks:
      - mynetwork

  scraping:
    container_name: scraping
    build:
      context: ./scraping_service
    platform: linux/x86_64
    volumes:
      - ./scraping_service:/rails
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3003:3000
    networks:
      - mynetwork

  tasks:
    container_name: tasks
    build:
      context: ./task_service
    platform: linux/x86_64
    volumes:
      - ./task_service:/rails
    depends_on:
      - db
      - auth
      - notifications
      - scraping
    env_file:
      - .env
    ports:
      - 3004:3000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge