services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  auth_service:
    build:
      context: ./auth_service
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    ports:
      - "3001:3000"

  notification_service:
    build:
      context: ./notification_service
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    ports:
      - "3002:3000"

  scraping_service:
    build:
      context: ./scraping_service
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    ports:
      - "3003:3000"

  task_service:
    build:
      context: ./task_service
    depends_on:
      - db
      - auth_service
      - notification_service
      - scraping_service
    environment:
      DATABASE_HOST: db
    ports:
      - "3004:3000"

volumes:
  db_data:
