Rails:
  Enabled: true

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true