# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'bootsnap', require: false
gem 'devise', '~> 4.9'
gem 'devise-argon2', '~> 2.0'
gem 'devise-i18n', '~> 1.12'
gem 'devise-jwt', '~> 0.12.1'
gem 'mysql2', '~> 0.5'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'rubocop'
  gem 'rubocop-rails'
end
