# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'bootsnap', require: false
gem 'devise', '~> 4.9'
gem 'devise-argon2', '~> 2.0'
gem 'devise-i18n', '~> 1.12'
gem 'devise-jwt', '~> 0.12.1'
gem 'dotenv-rails'
gem 'jbuilder'
gem 'mysql2', '~> 0.5'
gem 'puma', '>= 5.0'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'
gem 'rails-i18n', '~> 7.0', '>= 7.0.9'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'brakeman'
  gem 'bundler-audit'
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails', '~> 6.4', '>= 6.4.3'
  gem 'faker', '~> 3.3', '>= 3.3.1'
  gem 'fuubar', '~> 2.5', '>= 2.5.1'
  gem 'parallel_tests'
  gem 'rspec', '~> 3.13'
  gem 'rspec-json_expectations'
  gem 'rspec-rails', '~> 6.1', '>= 6.1.2'
  gem 'rubocop'
  gem 'rubocop-capybara'
  gem 'rubocop-factory_bot'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'rubocop-rspec_rails'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'database_cleaner'
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers', '~> 6.0'
  gem 'simplecov'
  gem 'simplecov-console'
end
