
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  port: 3306
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOST'] %>


development:
  <<: *default
  database: <%= ENV["DATABASE_DEV"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_PROD"] %>
